### ISSUE TITLE
Split and global state

### ISSUE THREAD

**Issue by jwmerrill** [mgold/elm-random-pcg#1]
Previous discussion: https://groups.google.com/d/msg/elm-dev/n9EwDQeFU5I/joCIYE8qBQAJ

@mgold wrote

> Regarding splitting: PCG has 64 bits of state, and a 63-bit "incrementer" (it's always odd) that indicates which of the 2^63 possible PRNG sequences you are on. So, no need to figure out how to mix some history of splitting into the RNG, you just change the incrementer. And for a pure implementation, you've got the right idea: keep track of your position in the binary tree and map that onto the space of incrementers. The problem is that you can only split a seed 63 times then. And, adjacent incrementers provide nearly-identical results. (Essentially, each time you split, you divide the space of possible incrementers available to that seed in half, one for each new seed, so they don't run over each other.)
> 
> I've implemented split, but it's impure. Basically there's a piece of shared state that tracks how many split have occurred (plus one), and when you want to do a split, it adds that number to the more significant half of the incrementer, so they're far apart. Then it steps each seed to the next value (in testing, it worked better). Even as implemented you could split a few million times and be fine. Why do I think it's okay to do this in an impure way? The only way you'd notice is if you called split on the same seed twice, and you're not supposed to do that. Seeds are opaque, so you're not supposed to inspect or equate them. The implementation is still deterministic; any program can be rerun with identical results. And, as I just described, I don't think it's acceptable to do this in a pure way since it limits the number of splits to something you could conceivably hit.

I think it's probably a mistake to implement split with global state. Because Elm is single threaded, I think it's probably true that running the same program twice (with all the same event inputs, of course) will return the same output, but you might still have situations where changes to the program that seem like they should leave its output the same actually don't.

The idea of hashing the binary tree position is so that you are less likely to hit the same incremeter value even if you split more than 63 times. This is essentially what hashing is always for: to reduce the likelihood of collisions when you are mapping a sparse subset of some large set into some smaller one.

**Comment by mgold** [comment]
I'll have to mull over exactly how hashing the tree position would work (pointers appreciated), but if it _can_ work, I'm not opposed. Especially since that would open the door to porting this to Elm proper, which means I could publish it, assuming the perf falloff isn't too bad.

> You might still have situations where changes to the program that seem like they should leave its output the same actually don't.

Yes, if I have a component that does a split, and the programmer adds a call to `split` upstream, the result changes. But it's also splitting a different seed, so that would happen anyway, right? Again, I think it's only possible to observe the impurity if you reuse seeds.

**Comment by mgold** [comment]
I've pushed a version implemented in Elm. It takes 10 seconds to generate 720000 random numbers; the Native implementation takes 9. So not too bad. (The core implementation also takes around 10 seconds.)

I understand it's Thanksgiving, so this might get punted to next week on my end if not yours, but I'm interested in how you'd do a good pure split.

**Comment by jwmerrill** [comment]
I'm mulling it over, but I don't know what to say yet.

**Comment by mgold** [comment]
So here's a dumb idea: what if we just pulled random numbers to create the second seed. According to [this post](https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d#.6o0zenmzz) (good but long read), you can draw n numbers from a psuedorandom source and consider it to be random if the period is >n^2. Since the period is 2^32 and we'll be splitting only dozens of times, this should be fine, right? But I'm skeptical since such a strategy could work for the standard library, in which case wouldn't it have been done already?

I also implemented `Random.PCG.Interop.fission` on a similar principle.

**Comment by jwmerrill** [comment]
Yeah, in some ways that seems like the "obvious" answer, and I don't
understand why it isn't ok, if it isn't.

**Comment by mgold** [comment]
If you implemented split in core as `let (i, seed') = generate gen seed in (initialSeed i, seed')`, you have no guarantees about where the new seed is in the cycle. It might reproduce numbers that have already been seen, or that will be seen later. By contrast, with PCB's 2^63 independent "streams", you can use a random number to make a seed that is nowhere on the cycle of numbers it came from. (I mean, maybe by chance you'll generate the current stream number, but I consider that so unlikely as not to be worth checking, but you could.)

**Comment by mgold** [comment]
I thought about contacting the PCG author, but I'm going to go with this method of generating random seeds. Thanks for your help @jwmerrill.

**Comment by mgold** [comment]
Here's what Melissa (author of PCG) said in an email:

> The problem with your approach is that while it may seem to work well in practice, there is no evidence that it does not have any bad pathologies.   For example, can you be sure be sure that if you split the generator, generate 1000 numbers and then split it again you might not get back to a state you've already been in?
> 
> From a practical standpoint, it "probably won't happen", but people have been burned by that before.  In many of the early implementations of the RNG arc4random, 1 time in 75,000, the period of the generator could be tiny, producing only 16320 integers before repeating.
> 
> It's something I'm thinking about, but for me to provide this feature I'll have to have an implementation scheme I'm happy about.  I may yet end up with a probabilistic scheme similar to yours but I'm still thinking about it.

I don't have a satisfactory proof, but here are some inklings: one of the new seeds is merely the input seed stepped a few times, and as such, won't go back to a previous state. As for the other seed, it's the increment that matters (identical state but a different increment is okay). And because the increment must be odd, so we throw away the last bit, n and n+1 (for odd n) both produce the same increment. So it is indeed a merely probabilistic guarantee.

The properties of PCG are that as long each split seed has a unique increment, everything will be fine. So the odds are that of hitting a 2-number-wide target in a sea of 2^32 numbers twice. I don't think empirical tests will be helpful -- either you get unlucky or you don't. There's nothing that could be _subtly_ wrong.

On the other hand, she didn't say it's completely and ridiculously wrong, so I think I'm okay with it. (There are easier-to-find bugs in the language and standard library...)
