### ISSUE TITLE
Identical values when generating rapidly

### ISSUE THREAD

**Issue by pukkamustard** [mgold/elm-random-pcg#14]
When generating values very rapidly they are identical.

Reproducible example:
https://runelm.io/c/ca4

This does not happen with the core `Random`.

**Comment by pukkamustard** [comment]
Haven't had time to dig into the code yet. But I assume the seed is not properly updated after each generation.

**Comment by mgold** [comment]
cc @rtfeldman

This is because `Random.generate` [relies](https://github.com/mgold/elm-random-pcg/blob/master/src/Random/Pcg.elm#L105-L109) on the current time. This is in some sense a limitation of third-party libraries, since I can't have the runtime store the seed between commands.

The easiest fix is for you to use the library correctly and call `Random.Pcg.list` instead of making many commands. But supposing this example is isolated from a real example where multiple components are making independent commands, you can use this library's `independentSeed` function.

Barring that, we can base `Random.generate` on core's random seed. That's really not so great, since it ties us to the statistically inferior core implementation, but I suppose it's better than the even-less-random current time. It will probably be slower, though.

**Comment by rtfeldman** [comment]
The real fix would be for this library to get whitelisted so it can have an effect manager—or for it to replace core `Random`, which already implements `generate` using an effect manager.

cc @evancz

**Comment by mgold** [comment]
There's a PR out to replace the guts of the RNG in core, and *most* of the other features could be handled by random-extra. In an attempt to keep that PR small, it does not include the splittable/independent feature that elm-test relies on. So I think this library will be around for awhile.

**Comment by mgold** [comment]
Closing. If you encounter this, track seeds manually (i.e. `step` not `generate`).
