### ISSUE TITLE
0.19 Upgrade plan

### ISSUE THREAD

**Issue by pdamoc** [mgold/elm-random-pcg#20]
This library is a dependency for the test infrastructure. 

Here are the changes that need to happen: 

- [ ] handle variable shadowing 
- [ ] switch from `List` to `List.Nonempty` for `frequency` and `choices` (something like this is needed because of the removal of `Debug.crash`)
- [ ] adapt the encoding to the new `Json.Encode.list` API

If this proposed solution for handling the removal of `Debug.crash` is OK I could create a PR to update the library.

**Comment by mgold** [comment]
This library will [no longer be a dependency](https://github.com/elm/random) for the test infrastructure. Work is already underway to upgrade elm-test, mostly by Noah and Aaron VH.

That said I intend to upgrade this library to maintain compatibility. I appreciate that you've pointed out the main hurdles but I'd like to handle it myself. It's not urgent because it's not blocking elm-test.
